### ISSUE TITLE
Problem with reloading

### ISSUE THREAD

**Issue by AntonUden** [psqnt/psqnt.github.io#1]
Page displays game over message multiple times before reloading

**Comment by psqnt** [comment]
pushed in a fix for this. Give it a test yourself, I tested on chrome, safari and brave and the problem should be solved.

I put `requestanimationframe(main)` into an else statement when `gameover` becomes true.

The problem was the alert was showing up but requestanimationframe must've continued to be called very quickly. (I think).

**Comment by AntonUden** [comment]
it works now
